language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/redux-prefabs-common
  email:
    secure: JTvQ11Ag5wtL+vvZLV67a+xMifgQjREHoht14j8L6XpaLiAQO1Lq0VyOcBv/RzPVyCnuKSLim2vEuxUI2BOySQabSTjwJJpeii+TW9TrSOszJxGekCT1FJuFxyXRhShdOjqjLPtubU4sVAK9UkgwjSguEjkRjB/n5kQtXVlXWDAdu1fyyPRZrPMXgPcPXk/SwHkdaxR+Jtyb3CYKnimfi61vRwezbrou7HVfEpdiPf631q1Ww/Z+sqp1N9+SXiNLtDB3GGOoGRg+5U0/U3lwS8CuzteSI57fsVJ3acE74OsFrPvp7WZP7SqB/M7cxY95FU9oRWaCtmMoA7HylT+KqkHEP4sSzIi0UsXrhgxChiwv72v0HRJP7w0HzmUmyroQQXjk0drZFnLhLLU5pQg8vvYtyQeYNfOm7/x9asQetUrhhyfPPPtkhb2lEfc7nxSCEuv/krbnK65RBEs2I6YLoy0TXnojjt0pByWURrkx57+RPZXePC6PihwmnHa9HFP8G5JwAyKWRVK3oXkCRoofXe3mUZzP+MeQs2xhS8EwRAhh0+b5s9Okfm61vZQR6ZVmuY5HFEZFW5WIRE7d8aFe5cjEyfov4kF5f0JI9Efc3e8heRtXPVv0V0oLweVkwRzn6cXpqI2mTUWAdQx/GlfSkCTE5G8DO1ToFP6S4bnZBBI=
  api_key:
    secure: GlwKH9NRWJzsXdQShfVLDkXKjFnunaJYfmlgsMi66TmxZ44M7++T3NwpaJ577ZesvnSNJVD0Vt5uSjVSaptUjixLoxIJfnHnC/UHfJtFxeRXcmtmlBjdoEkSUBp26JVYgIAjyNPUMsEQ2L/M/yHZxO1d7SVqSkD42/ltMYsbuyJFsLa1M/smDFclMzETLTFWnm6Vne472SbXbMHg88NhD6htazXmy0As9BKxrVxx71HvK9M3YrGodM8VOyeOLYFz23N80+/aLQyVhmsKimjAHrVBAMmKpEsxoWNniWmtiK839II80P/vlBvjNh4HdbcGLs/NvAvpndCo5fKKAhQnq0F7Mm0zZev4W3WV0XXpRK2NHN6csZasrGu0WUn6v4opCVohkTHktWXZxhVoMa18HH1oyAkEDsPQe/w8UCdzLO8LcwNv8i2aP7rllCXDQWvBkX3tyrpipfpbwLzxPJarZ5hntEeCDZDvUhTe+ke6bRtdGw3mcVPpxkBGlWGoGJaGa/wzDiK+mmY5P96yLAnUIKohpi3mZB6h4zYMi9MJe9REJWf7hSuWASh0cIzd4aHRf0wwKM77mqwLmWBhcsSL9wUMVnQATuV/9OACGalr355Z21e29yh8uaIJ/mgq9B2VNMbKDXvxCu3AsPBHyQmulmfpZjOHetSRmsS2tAUeVyI=
